"""add garmin sync tracking to plan_workouts

Revision ID: a03e9bf9b7c0
Revises: 9c1ca29a5035
Create Date: 2026-07-11 23:41:23.646918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a03e9bf9b7c0'
down_revision: Union[str, None] = '9c1ca29a5035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_workouts', sa.Column('garmin_workout_id', sa.String(), nullable=True))
    op.add_column('plan_workouts', sa.Column('garmin_scheduled_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_workouts', 'garmin_scheduled_id')
    op.drop_column('plan_workouts', 'garmin_workout_id')
    # ### end Alembic commands ###
